bot:
  abi_migration_branches:
  - 1.15.x
  - 1.14.x
build_platform:
  osx_arm64: osx_64
build_with_mambabuild: false
conda_forge_output_validation: true
provider:
  linux_aarch64: default
  linux_ppc64le: default
  win: azure
test: native
test_on_native_only: true
